version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
  - package-ecosystem: "pip"
    directory: "/GridboxConnectorAddon-edge/GridboxConnector"
    schedule:
      interval: "weekly"
      time: "13:00"
      day: "sunday"

