[tool.bumpversion]
current_version = "2.11.67"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""
[[tool.bumpversion.files]]
filename="./GridboxConnectorAddon/config.yaml"
[[tool.bumpversion.files]]
filename="./GridboxConnectorAddon/rootfs/share/cloudSettings.json"
[[tool.bumpversion.files]]
filename="./GridboxConnectorAddon-dev/config.yaml"
[[tool.bumpversion.files]]
filename="./GridboxConnectorAddon-dev/rootfs/share/cloudSettings.json"