# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base-python/aarch64:17.0.0"
  amd64: "ghcr.io/hassio-addons/base-python/amd64:17.0.0"
labels:
  org.opencontainers.image.title: "Viessmann Gridbox Connector (Edge)"
  org.opencontainers.image.description: "Development of Viessmann Gridbox Connector"
  org.opencontainers.image.source: "https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
