# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.16"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Viessmann Gridbox Connector"
  org.opencontainers.image.description: "Get the pv data from the Viessmann Cloud"
  org.opencontainers.image.source: "https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
