name: Bump Version
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Select the version type"
        required: true
        type: choice
        default: "patch"
        options:
          - major
          - minor
          - patch
          - dev
      type:
        description: "Select Type"
        required: true
        type: choice
        default: "edge"
        options:
          - dev
          - edge

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6

      - run: pip install bump-my-version

      - name: Get Old Version
        run: |
          echo "OLD_VERSION=$(bump-my-version show --config-file .bumpversion-${{ github.event.inputs.type }}.toml current_version)" >> $GITHUB_ENV

      - name: Bump Version
        run: ./bumpversion-${{ github.event.inputs.type }}.sh ${{ github.event.inputs.version }}

      - name: Get New Version
        run: |
          echo "NEW_VERSION=$(bump-my-version show --config-file .bumpversion-${{ github.event.inputs.type }}.toml current_version)" >> $GITHUB_ENV

      - name: Commit and Tag
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: bump ${{ github.event.inputs.type }} ${{ env.OLD_VERSION }} -> ${{ env.NEW_VERSION }}"
