name: Release Stable
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Copy Release
        run: ./copy_to_release.sh

      - name: Commit Stable
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "release: Release Stable Version"
